// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home

import { supabase } from '../lib/Store';
import { useState } from 'react';
import { useRouter } from 'next/router';
const Home = () => {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const router = useRouter()
  const handleLogin = async(type:string, username:string, password:string) => {
    try {
      const {error, user} = 
        type === 'LOGIN'
          ? await supabase.auth.signIn({email: username, password})
          : await supabase.auth.signUp({email: username, password})
      console.log('login signUp user', user)
      if (error) {
        console.log('login signup エラーです！')
        alert(`Error with auth: ${error.message}`)
      } else if (!user) {
        // alert('Sign up successful, confirmation mail should be sent soon!')
        // console.log('Sign up successful, confirmation mail should be sent soon!')
      }
    } catch(error:any) {
      console.log('login signup エラーハンドリング！', error)
      alert(error)
    }
  }
  return (
    <div className='w-full h-full flex justify-center items-center p-4 bg-gray-300'>
      <div className='w-full sm:w-1/2 xl:w-1/3'>
        <div className='border-teal-500 p-8 border-t-18 bg-white mb-6 rounded-lg shadow-lg' >
          <div className='mb-4'>
            <label className='font-bold text-gray-800 block mb-2'>Email</label>
            <input
              type="text"
              className='block appearance-none w-full bg-white border border-gray-200 hover:border-gray-400 p-2 rounded shadow'
              placeholder="Your username"
              value={username}
              onChange={e => setUsername(e.target.value)}
            />
          </div>
          <div className='mb-4'>
            <label className='font-bold text-gray-800 block mb-2'>Password</label>
            <input
              type="password"
              className='block appearance-none w-full bg-white border border-gray-200 hover:border-gray-400 p-2 rounded shadow'
              placeholder="Your password"
              value={password}
              onChange={e => setPassword(e.target.value)}
            />
          </div>
          <div className='flex flex-col gap-2'>
            <a
              className='bg-indigo-700 text-white py-2 px-4 rounded text-center transition duration-150 hover:bg-indigo-600'
              href={'/'}
              // href={'/channels'}
              onClick={e => {
                e.preventDefault()
                handleLogin('SIGNUP', username, password)
              }}>
              Sign up
            </a>
            <a
              className='border border-indigo-700 text-indigo-700 py-2 px-4 rounded text-center transition duration-150 hover:bg-indigo-700 hover:text-white'
              // href={'/'}
              // href={'/channels'}
              onClick={e => {
                e.preventDefault()
                handleLogin('LOGIN', username, password)
                router.push('/channels/[id]', '/channels/1')
              }}>
              Login
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home